[manifest]
dump_lua = true
priority = 0
version = "1.4.0"

[[patches]]
[patches.pattern]
match_indent = false
pattern = '''
function Card:can_use_consumeable(any_state, skip_check)
'''
payload = '''
function Card:can_use_consumeable(any_state, skip_check)
  if not self.ability.consumeable then return false end
'''
position = "at"
target = "card.lua"
times = 1
